# Generated by Django 3.0.6 on 2020-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200515_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('IA', 'Неактивна'), ('A', 'Активна')], default='IA', max_length=2),
        ),
    ]
