# Generated by Django 3.0.6 on 2020-05-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200514_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('USR', 'Пользователь'), ('RED', 'Редактор'), ('ADM', 'Админ')], default='USR', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1),
        ),
    ]
